[book]
title = "InkGen Documentation"
author = "OctoFHIR Team"
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
theme = "InkGen"
mathjax-support = false
edit-url-template = "https://github.com/octofhir/inkgen/edit/main/docs/book/{path}"

[output.html.fold]
enable = true
level = 2

[build]
build-dir = "build"
create-missing = false
use-default-preprocessors = true

[preprocessor.links]
