//! FHIR interoperability utilities for TypeScript generation.
//!
//! This module generates TypeScript helpers for common FHIR interop patterns:
//! - Typed references with compile-time resource type checking
//! - Date/time parsing and formatting for FHIR primitives
//! - Bundle traversal and reference resolution
//! - Search parameter interfaces and URL builders
//!
//! These utilities reduce boilerplate code in applications consuming the generated SDK.

pub mod bundles;
pub mod dates;
pub mod references;
pub mod search;

pub use bundles::{BundleConfig, BundleHelpers};
pub use dates::{DateConfig, DateHelpers};
pub use references::{ReferenceConfig, ReferenceHelpers};
pub use search::{SearchConfig, SearchHelpers};

use serde::Serialize;

/// Master configuration for interop utility generation
#[derive(Debug, Clone, Serialize)]
pub struct InteropConfig {
    /// Enable typed Reference<T> helpers
    pub typed_references: bool,
    /// Enable date/time parsing and formatting
    pub date_helpers: bool,
    /// Enable Bundle traversal utilities
    pub bundle_traversal: bool,
    /// Enable search parameter helpers
    pub search_helpers: bool,
    /// Specific configurations for each module
    pub reference_config: ReferenceConfig,
    pub date_config: DateConfig,
    pub bundle_config: BundleConfig,
    pub search_config: SearchConfig,
}

impl Default for InteropConfig {
    fn default() -> Self {
        Self {
            typed_references: true,
            date_helpers: true,
            bundle_traversal: true,
            search_helpers: true,
            reference_config: ReferenceConfig::default(),
            date_config: DateConfig::default(),
            bundle_config: BundleConfig::default(),
            search_config: SearchConfig::default(),
        }
    }
}

/// Interop utility generator context
#[derive(Debug, Clone, Serialize)]
pub struct InteropGenerator {
    /// Resource types available for generation
    pub resource_types: Vec<String>,
    /// Search parameters loaded from FHIR package
    #[serde(skip)]
    pub search_parameters: Vec<inkgen_core::SearchParameterInfo>,
    /// Whether typed references are enabled
    pub has_references: bool,
    /// Whether date helpers are enabled
    pub has_dates: bool,
    /// Whether bundle helpers are enabled
    pub has_bundles: bool,
    /// Whether search helpers are enabled
    pub has_search: bool,
}

impl InteropGenerator {
    /// Create a new interop generator
    pub fn new(
        resource_types: Vec<String>,
        search_parameters: Vec<inkgen_core::SearchParameterInfo>,
        config: &InteropConfig,
    ) -> Self {
        Self {
            resource_types,
            search_parameters,
            has_references: config.typed_references,
            has_dates: config.date_helpers,
            has_bundles: config.bundle_traversal,
            has_search: config.search_helpers,
        }
    }

    /// Generate all interop utilities
    ///
    /// Returns TypeScript code for all enabled interop features
    pub fn generate_all(&self, config: &InteropConfig) -> String {
        let mut parts = vec![
            "// FHIR Interoperability Utilities".to_string(),
            "// Auto-generated by InkGen - do not edit manually".to_string(),
        ];

        // Generate imports
        parts.push(self.generate_imports());

        // Generate typed references
        if self.has_references {
            parts.push("\n// ========== Typed References ==========".to_string());
            let ref_helpers =
                ReferenceHelpers::new(self.resource_types.clone(), &config.reference_config);
            parts.push(ref_helpers.generate_all());
        }

        // Generate date helpers
        if self.has_dates {
            parts.push("\n// ========== Date/Time Utilities ==========".to_string());
            let date_helpers = DateHelpers::new(&config.date_config);
            parts.push(date_helpers.generate_all());
        }

        // Generate bundle helpers
        if self.has_bundles {
            parts.push("\n// ========== Bundle Utilities ==========".to_string());
            let bundle_helpers = BundleHelpers::new(&config.bundle_config);
            parts.push(bundle_helpers.generate_all());
        }

        // Generate search helpers
        if self.has_search {
            parts.push("\n// ========== Search Parameters ==========".to_string());
            let search_helpers = SearchHelpers::new(
                self.resource_types.clone(),
                self.search_parameters.clone(),
                &config.search_config,
            );
            parts.push(search_helpers.generate_all());
        }

        parts.join("\n\n")
    }

    /// Generate interop utilities without search parameters
    ///
    /// This generates references, dates, and bundles, but excludes search.
    /// Search parameters are generated separately in split files.
    pub fn generate_without_search(&self, config: &InteropConfig) -> String {
        let mut parts = vec![
            "// FHIR Interoperability Utilities".to_string(),
            "// Auto-generated by InkGen - do not edit manually".to_string(),
        ];

        // Generate imports (excluding search-related imports)
        parts.push(self.generate_imports_without_search());

        // Generate typed references
        if self.has_references {
            parts.push("\n// ========== Typed References ==========".to_string());
            let ref_helpers =
                ReferenceHelpers::new(self.resource_types.clone(), &config.reference_config);
            parts.push(ref_helpers.generate_all());
        }

        // Generate date helpers
        if self.has_dates {
            parts.push("\n// ========== Date/Time Utilities ==========".to_string());
            let date_helpers = DateHelpers::new(&config.date_config);
            parts.push(date_helpers.generate_all());
        }

        // Generate bundle helpers
        if self.has_bundles {
            parts.push("\n// ========== Bundle Utilities ==========".to_string());
            let bundle_helpers = BundleHelpers::new(&config.bundle_config);
            parts.push(bundle_helpers.generate_all());
        }

        parts.join("\n\n")
    }

    /// Generate TypeScript imports for interop utilities
    fn generate_imports(&self) -> String {
        let mut imports = vec![];

        // Import Reference from index (always available)
        if self.has_references || self.has_bundles {
            imports.push("import type { Reference } from '../index';");
        }

        // Import Resource directly (not in index)
        if self.has_references || self.has_bundles {
            imports.push("import type { Resource } from '../resource';");
        }

        // Import date/coding types from index
        if self.has_dates {
            imports.push("import type { Coding, CodeableConcept } from '../index';");
        }

        // Import Bundle types directly (not in index)
        if self.has_bundles {
            imports.push("import type { Bundle, BundleEntry } from '../bundle';");
        }

        if imports.is_empty() {
            String::new()
        } else {
            format!("// Type imports\n{}", imports.join("\n"))
        }
    }

    /// Generate TypeScript imports for interop utilities (without search)
    fn generate_imports_without_search(&self) -> String {
        // Same as generate_imports since search has its own import management
        self.generate_imports()
    }

    /// Check if any interop utilities are enabled
    pub fn is_enabled(&self) -> bool {
        self.has_references || self.has_dates || self.has_bundles || self.has_search
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_interop_config_default() {
        let config = InteropConfig::default();
        assert!(config.typed_references);
        assert!(config.date_helpers);
        assert!(config.bundle_traversal);
        assert!(config.search_helpers);
    }

    #[test]
    fn test_interop_generator_new() {
        let config = InteropConfig::default();
        let resource_types = vec!["Patient".to_string(), "Observation".to_string()];
        let search_params = Vec::new();
        let generator = InteropGenerator::new(resource_types.clone(), search_params, &config);

        assert_eq!(generator.resource_types, resource_types);
        assert!(generator.has_references);
        assert!(generator.has_dates);
        assert!(generator.has_bundles);
        assert!(generator.has_search);
    }

    #[test]
    fn test_is_enabled() {
        let config = InteropConfig::default();
        let generator = InteropGenerator::new(vec![], vec![], &config);
        assert!(generator.is_enabled());

        let disabled_config = InteropConfig {
            typed_references: false,
            date_helpers: false,
            bundle_traversal: false,
            search_helpers: false,
            ..Default::default()
        };
        let disabled_generator = InteropGenerator::new(vec![], vec![], &disabled_config);
        assert!(!disabled_generator.is_enabled());
    }

    #[test]
    fn test_generate_imports() {
        let config = InteropConfig::default();
        let generator = InteropGenerator::new(vec!["Patient".to_string()], vec![], &config);

        let imports = generator.generate_imports();
        assert!(imports.contains("Reference"));
        assert!(imports.contains("Resource"));
        assert!(imports.contains("Bundle"));
    }

    #[test]
    fn test_generate_all() {
        use inkgen_core::SearchParameterInfo;
        use serde_json::json;

        let config = InteropConfig::default();
        let resource_types = vec!["Patient".to_string(), "Observation".to_string()];

        // Create mock search parameters
        let patient_param = SearchParameterInfo::from_json(&json!({
            "resourceType": "SearchParameter",
            "code": "name",
            "base": ["Patient"],
            "type": "string",
            "description": "Patient name"
        }))
        .unwrap();

        let search_params = vec![patient_param];
        let generator = InteropGenerator::new(resource_types, search_params, &config);

        let code = generator.generate_all(&config);

        // Should contain section headers
        assert!(code.contains("Typed References"));
        assert!(code.contains("Date/Time Utilities"));
        assert!(code.contains("Bundle Utilities"));
        assert!(code.contains("Search Parameters"));

        // Should contain generated code from each module
        assert!(code.contains("TypedReference"));
        assert!(code.contains("parseFHIRDate"));
        assert!(code.contains("getResourcesOfType"));
        assert!(code.contains("PatientSearchParams"));
    }

    #[test]
    fn test_selective_generation() {
        let config = InteropConfig {
            typed_references: true,
            date_helpers: false,
            bundle_traversal: false,
            search_helpers: false,
            ..Default::default()
        };
        let generator = InteropGenerator::new(vec!["Patient".to_string()], vec![], &config);

        let code = generator.generate_all(&config);

        // Should only contain references
        assert!(code.contains("TypedReference"));
        assert!(!code.contains("parseFHIRDate"));
        assert!(!code.contains("getResourcesOfType"));
        assert!(!code.contains("PatientSearchParams"));
    }
}
