[package]
name = "inkgen-typescript"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
indexmap = { workspace = true }
tera = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
async-trait = { workspace = true }
once_cell = "1"

inkgen-core = { path = "../inkgen-core" }

[dev-dependencies]
inkgen-testing = { path = "../inkgen-testing" }
insta = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
